# Generated by Django 4.2 on 2024-07-07 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_payment_link_payment_session_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="payment_method",
            field=models.CharField(
                choices=[("CASH", "Наличными"), ("TRANSFER", "Перевод на счет")],
                default="TRANSFER",
                max_length=30,
                verbose_name="Способ оплаты",
            ),
        ),
    ]
